/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_one_mvp_ui_maintab_fragment_ReadingFragment */

#ifndef _Included_com_one_mvp_ui_maintab_fragment_ReadingFragment
#define _Included_com_one_mvp_ui_maintab_fragment_ReadingFragment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_one_mvp_ui_maintab_fragment_ReadingFragment
 * Method:    SayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_one_mvp_ui_maintab_fragment_ReadingFragment_SayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
